/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_app_framework_jni_AppNativeUtil */

#ifndef _Included_com_app_framework_jni_AppNativeUtil
#define _Included_com_app_framework_jni_AppNativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_app_framework_jni_AppNativeUtil
 * Method:    buildReqKey
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_app_framework_jni_AppNativeUtil_buildReqKey
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
